config/routes.rb
Rails.application.routes.draw do
  resources :product_categories

  resources :categories

  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true
  has_many :product_categories
  has_many :products, :through => :product_categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  has_many :product_categories
  has_many :categories, :through => :product_categories
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_category, only: [:show, :edit, :update, :destroy]

  # GET /product_categories
  # GET /product_categories.json
  def index
    @product_categories = ProductCategory.all
  end

  # GET /product_categories/1
  # GET /product_categories/1.json
  def show
  end

  # GET /product_categories/new
  def new
    @product_category = ProductCategory.new
  end

  # GET /product_categories/1/edit
  def edit
  end

  # POST /product_categories
  # POST /product_categories.json
  def create
    @product_category = ProductCategory.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to @product_category, notice: 'Product category was successfully created.' }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1
  # PATCH/PUT /product_categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to @product_category, notice: 'Product category was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1
  # DELETE /product_categories/1.json
  def destroy
    @product_category.destroy
    respond_to do |format|
      format.html { redirect_to product_categories_url, notice: 'Product category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = ProductCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_category_params
      params.require(:product_category).permit(:product_id, :category_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product.save
    respond_with(@product)
    flash[:notice] = 'Product was successfully created'
    # @product = Product.new(product_params)
    #
    # respond_to do |format|
    #   if @product.save
    #     format.html { redirect_to @product, notice: 'Product was successfully created.' }
    #     format.json { render :show, status: :created, location: @product }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @product.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, category_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
'|
= link_to 'Back', categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkedModelsTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product_categories/_form.html.slim
= form_for @product_category do |f|
  - if @product_category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product_category.errors.count, "error")} prohibited this product_category from being saved:"
      ul
        - @product_category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :product
    = f.text_field :product
  .field
    = f.label :category
    = f.text_field :category
  .actions = f.submit

app/views/product_categories/edit.html.slim
h1 Editing product_category

== render 'form'

= link_to 'Show', @product_category
'|
= link_to 'Back', product_categories_path

app/views/product_categories/index.html.slim
h1 Listing product_categories

table
  thead
    tr
      th Product
      th Category
      th
      th
      th

  tbody
    - @product_categories.each do |product_category|
      tr
        td = product_category.product
        td = product_category.category
        td = link_to 'Show', product_category
        td = link_to 'Edit', edit_product_category_path(product_category)
        td = link_to 'Destroy', product_category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product category', new_product_category_path

app/views/product_categories/new.html.slim
h1 New product_category

== render 'form'

= link_to 'Back', product_categories_path

app/views/product_categories/show.html.slim
p#notice = notice

p
  strong Product:
  = @product_category.product
p
  strong Category:
  = @product_category.category

= link_to 'Edit', edit_product_category_path(@product_category)
'|
= link_to 'Back', product_categories_path

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

  =collection_check_boxes(:product, :category_ids, Category.all, :id, :name) do |b|
    -b.label { b.check_box + b.text }

  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

= link_to 'Show', @product
'|
= link_to 'Back', products_path

app/views/products/index.html.slim
h1 Listing products

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        td = link_to 'Destroy', product, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Product', new_product_path

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name

-@product.categories.each do |category|
  p =category.name

= link_to 'Edit', edit_product_path(@product)
'|
= link_to 'Back', products_path